check go mod tidy

diff --git a/workflow-templates/go-check.yml b/workflow-templates/go-check.yml
--- a/workflow-templates/go-check.yml
+++ b/workflow-templates/go-check.yml
@@ -11,7 +11,15 @@ jobs:
           go-version: "1.16.x"
       - name: Install staticcheck
         run: go install honnef.co/go/tools/cmd/staticcheck@be534f007836a777104a15f2456cd1fffd3ddee8 # v2020.2.2
+      - name: Check that go.mod is tidy
+        run: |
+          cp go.mod go.mod.orig
+          cp go.sum go.sum.orig
+          go mod tidy
+          diff go.mod go.mod.orig
+          diff go.sum go.sum.orig
       - name: go vet
+        if: ${{ success() || failure() }} # run this step even if the previous one failed
         run: go vet ./...
       - name: staticcheck
         if: ${{ success() || failure() }} # run this step even if the previous one failed
