fail dispatch if PR creation failed

diff --git a/.github/workflows/dispatch.yml b/.github/workflows/dispatch.yml
--- a/.github/workflows/dispatch.yml
+++ b/.github/workflows/dispatch.yml
@@ -121,12 +121,13 @@ jobs:
             (( page+=1 ))
           done
           echo "::set-output name=targets::$(jq -nc '$ARGS.positional' --args ${targets[@]})"
-      - name: Create PRs in targets that need it
+      - name: Sync PRs in targets that need it
         env:
           PR_TITLE: 'sync: update CI config files'
           PR_BODY: 'Syncing to commit ${{ github.event.head_commit.url }}.'
           PR_BRANCH: 'web3-bot/sync'
         run: |
+          failed=()
           for target in $(jq -r '.[]' <<< ${{ toJson(steps.jobs.outputs.targets) }}); do
             base="$(gh api "/repos/${target}" --jq '.default_branch')"
             # tries to create a PR in target
@@ -134,15 +135,22 @@ jobs:
               echo "Successfully created a PR for '$target'"
             elif [[ "$(jq -r '.errors[0].message' <<< "$result")" == 'A pull request already exists'* ]]; then
               number="$(gh api "/repos/$target/pulls?head=${{ env.PR_BRANCH }}&per_page=1&state=open" --jq '.[0].number')"
+              # tries to update the PR in target
               if result="$(gh api -X PATCH "/repos/$target/pulls/$number" -f body="${{ env.PR_BODY }}" -f base="$base")"; then
                 echo "Successfully updated the PR for '$target'"
               else
                 echo "$result"
-                echo "::error ::Failed to update the PR for '$target'"
+                echo "Failed to update the PR for '$target'"
+                failed+=("$target(update)")
               fi
             else
               echo "$result"
-              echo "::error ::Failed to create a PR for '$target'"
+              echo "Failed to create a PR for '$target'"
+              failed+=("$target(create)")
             fi
             sleep 3
           done
+          if ((${#failed[@]})); then
+            echo "::error ::Failed to sync PRs in: ${failed[@]}"
+            exit 1
+          fi
