open PRs sequentially but continue updating branches in parallel (#261)
* move config*.json files to configs directory

* rename configs/*.json

* make checks aware of all the configs/*.json

* turn configs into objects with repositories key

* make files part of the config

* move language specific copy-workflow setup to actions

* make dispatch workflow support more than one config json

* create fewer batches if possible

* set up copy-workflow actions properly

* extract defaults from config separately

* bring back double toJson

* use copy-workflow actions from same branch

* use compact json representation for storing FILES

* fix files and local actions

* run actions from template repo

* add missing shell property to actions

* add configs README

* set deploy_versioning=true for go repositories

* address review comments

* restore hardcoded template-repo reference

* add section on config testing

* fix batches creation

* fix command that produces batches

* fix needs update logic

* use GitHub API sequentially to avoid rate limiting

* remove head_commit_url from copy-workflow inputs

* fix typo around WORKFLOW_REF

* use github.ref for WORFKLOW_REF

* create PRs through gh api

* fix error reporting

* fix header comment in dispatch workflow

* imporve comments in dispatch workflow

* retrieve jobs that executed step through api

* split dispatch job into distinct steps

* apply fixes from testing session

* use undocumented gh api endpoint to retrieve workflow runs

* add workflow watch delay

* improve the comments in dispatch workflow

* update PR if it already exists

* fail dispatch if PR creation failed

* simplify finding targets with --paginate

* do not suggest that GITHUB_USER is configurable in copy workflow

diff --git a/.github/workflows/dispatch.yml b/.github/workflows/dispatch.yml
--- a/.github/workflows/dispatch.yml
+++ b/.github/workflows/dispatch.yml
@@ -1,6 +1,6 @@
-# Trigger the execution of copy-workflow.yml, in batches of 8 repositories.
+# Trigger the execution of copy workflow in batches.
 # This workflow is needed since GitHub Actions limits the matrix size to 256 jobs.
-# We use one job per repository per file.
+# We use one job per repository per batch.
 
 on:
   push:
@@ -8,14 +8,20 @@ on:
 
 env:
   # Number of repositories in a batch.
-  # Deployment jobs in the same batch are run sequentially.
-  # With ~180 repos, this means we'll run around 9 instances of the copy workflow in parallel.
-  # This is (hopefully) sufficient to prevent us from triggering GitHub Action's abuse detection mechanism.
-  MAX_REPOS_PER_WORKFLOW: 20
+  # Matrix jobs within a copy workflow run are run in parallel.
+  # 256 is the upper limit on the number of matrix jobs.
+  # Batching too many repositories together can result in
+  #  could not create workflow dispatch event: HTTP 422: inputs are too large.
+  # This value should be higher than max-parallel in copy workflow.
+  MAX_REPOS_PER_WORKFLOW: 100
+  # Number of seconds to wait before starting to watch copy workflow run.
+  # Unfortunately, the interval on the watch is not configurable.
+  # The delay helps us save on GH API requests.
+  WORKFLOW_COMPLETION_CHECK_DELAY: 60
 
 jobs:
   matrix:
-    name: Trigger copy workflows
+    name: Batch targets
     runs-on: ubuntu-latest
     outputs:
       batches: ${{ steps.set-matrix.outputs.batches }}
@@ -42,6 +48,7 @@ jobs:
           echo "::set-output name=batches::$batches"
   dispatch:
     needs: [ matrix ]
+    name: Dispatch copy workflow(batch ${{ matrix.cfg.key }})
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
@@ -51,18 +58,87 @@ jobs:
         # For each "dispatch" job, matrix.cfg.value is an array, like:
         #
         #   [
-        #     {"target": "repo1", "files": [".github/workflows/go-check.yml"]}, 
+        #     {"target": "repo1", "files": [".github/workflows/go-check.yml"]},
         #     {"target": "repo2", "files": [".github/workflows/go-check.yml", ".github/workflows/go-test.yml"]}
         #   ]
         #
-        # The triggered copy-workflow jobs use that final array as their matrix.
-        # As such, we'll end up with one copy-workflow parallel job per target.
+        # The triggered copy workflow runs use that final array as their matrix.
+        # Since max-parallel here is 1, we'll end up with at most max-parallel from copy workflow + 1 parallel jobs.
+        # 20 is the upper limit on parallel jobs on a free plan.
         cfg: ${{ fromJson(needs.matrix.outputs.batches) }}
-    name: Start copy workflow (batch ${{ matrix.cfg.key }})
+      max-parallel: 1
+    env:
+      GITHUB_TOKEN: ${{ secrets.WEB3BOT_GITHUB_TOKEN }}
+      WORKFLOW_YML: copy-workflow.yml
+      WORKFLOW_REPO: protocol/.github
     steps:
-      - uses: benc-uk/workflow-dispatch@4c044c1613fabbe5250deadc65452d54c4ad4fc7 # v1.1.0
-        with:
-          workflow: "Deploy" # "name" attribute of copy-workflow.yml
-          token: ${{ secrets.WEB3BOT_GITHUB_TOKEN }}
-          # double toJson on matrix.cfg.value is here on purpose
-          inputs: '{ "head_commit_url": ${{ toJson(github.event.head_commit.url) }}, "targets": ${{ toJson(toJson(matrix.cfg.value)) }} }'
+      - id: dispatch
+        name: Dispatch copy workflow
+        run: |
+          start_date="$(date +%s)"
+          # 2 toJson calls are needed to turn the array of targets into a string
+          echo '{"targets":${{ toJson(toJson(matrix.cfg.value)) }}}' | jq -c '.' | gh workflow run "${{ env.WORKFLOW_YML }}" --ref "${{ github.ref }}" --repo "${{ env.WORKFLOW_REPO }}" --json
+          echo "::set-output name=start_date::$start_date"
+      - id: run
+        name: Wait for copy workflow run to start
+        run: |
+          # checks every 3 seconds until the most recent copy workflow run's created_at is later than this job's start_date
+          while sleep 3; do
+            run="$(gh api "/repos/${{ env.WORKFLOW_REPO }}/actions/workflows/${{ env.WORKFLOW_YML }}/runs?per_page=1" --jq '.workflow_runs[0]')"
+            # nothing to check if no copy workflow run was returned
+            if [[ ! -z "$run" ]]; then
+              run_start_date="$(date --date="$(jq -r '.created_at' <<< "$run")" +%s)"
+              if [[ "$run_start_date" > "${{ steps.dispatch.outputs.start_date }}" ]]; then
+                echo "::set-output name=id::$(jq -r '.id' <<< "$run")"
+                break
+              fi
+            fi
+          done
+      - name: Wait for copy workflow run to complete
+        run: |
+          # delays checking copy workflow's run status to save on GH API requests
+          sleep ${{ env.WORKFLOW_COMPLETION_CHECK_DELAY }}
+
+          # checks every 3 seconds until the copy workflow run's status is completed
+          # redirects the stdout to /dev/null because it is very chatty
+          gh run watch "${{ steps.run.outputs.id }}" --repo "${{ env.WORKFLOW_REPO }}" > /dev/null
+      - id: jobs
+        name: Find copy workflow jobs that pushed changes
+        env:
+          STEP_NAME: 'Force push web3-bot/sync branch'
+        run: |
+          targets="$(gh api --paginate '/repos/${{ env.WORKFLOW_REPO }}/actions/runs/${{ steps.run.outputs.id }}/jobs' | jq '.jobs | map(select(.steps[] | select(.name == "${{ env.STEP_NAME }}") and select(.conclusion == "success"))) | map(.name)' | jq -sc 'add')"
+          echo "::set-output name=targets::$targets"
+      - name: Sync PRs in targets that need it
+        env:
+          PR_TITLE: 'sync: update CI config files'
+          PR_BODY: 'Syncing to commit ${{ github.event.head_commit.url }}.'
+          PR_BRANCH: 'web3-bot/sync'
+        run: |
+          failed=()
+          for target in $(jq -r '.[]' <<< ${{ toJson(steps.jobs.outputs.targets) }}); do
+            base="$(gh api "/repos/${target}" --jq '.default_branch')"
+            # tries to create a PR in target
+            if result="$(gh api "/repos/$target/pulls" -f title="${{ env.PR_TITLE }}" -f body="${{ env.PR_BODY }}" -f head="${{ env.PR_BRANCH }}" -f base="$base")"; then
+              echo "Successfully created a PR for '$target'"
+            elif [[ "$(jq -r '.errors[0].message' <<< "$result")" == 'A pull request already exists'* ]]; then
+              number="$(gh api "/repos/$target/pulls?head=${{ env.PR_BRANCH }}&per_page=1&state=open" --jq '.[0].number')"
+              # tries to update the PR in target
+              if result="$(gh api -X PATCH "/repos/$target/pulls/$number" -f body="${{ env.PR_BODY }}" -f base="$base")"; then
+                echo "Successfully updated the PR for '$target'"
+              else
+                echo "$result"
+                echo "Failed to update the PR for '$target'"
+                failed+=("$target(update)")
+              fi
+            else
+              echo "$result"
+              echo "Failed to create a PR for '$target'"
+              failed+=("$target(create)")
+            fi
+            sleep 3
+          done
+          if ((${#failed[@]})); then
+            echo "::error ::Failed to sync PRs in: ${failed[@]}"
+            exit 1
+          fi
