fix: semver comparison for prereleases in release-check

diff --git a/.github/workflows/release-check.yml b/.github/workflows/release-check.yml
--- a/.github/workflows/release-check.yml
+++ b/.github/workflows/release-check.yml
@@ -50,24 +50,34 @@ jobs:
         if: steps.tag.outputs.exists == 'false'
         env:
           VERSION: ${{ steps.version.outputs.version }}
-        run: semver "$VERSION" # fails if the version is not a valid semver version (e.g. v0.1 would fail)
+        # semver fails if the version is not valid (e.g. v0.1 would fail)
+        run: semver "$VERSION"
+      - id: prerelease
+        if: steps.tag.outputs.exists == 'false'
+        name: Check if this is a pre-release
+        env:
+          VERSION: ${{ steps.version.outputs.version }}
+        # semver -r fails if the version is not valid or if it is a pre-release (e.g v0.1 or v0.1.0-rc1 would fail)
+        run: echo "prerelease=$(semver -r "$VERSION" && echo false || echo true)" >> $GITHUB_OUTPUT
       - id: prev
         name: Determine version number to compare to
         if: steps.tag.outputs.exists == 'false'
         env:
           VERSION: ${{ steps.version.outputs.version }}
+          PRERELEASE: ${{ steps.prerelease.outputs.prerelease }}
         # We need to determine the version number we want to compare to,
         # taking into account that this might be a (patch) release on a release branch.
         # Example:
-        # Imagine a module that has releases for v0.1.0, v0.2.0 and v0.3.0.
+        # Imagine a module that has releases for v0.1.0, v0.2.0, v0.3.0 and v0.3.0-rc1.
         # When trying to cut a release v0.2.1, we need to base our comparisons on v0.2.0.
         # When trying to cut a release v0.3.1 or v0.4.0, we need to base our comparisons on v0.3.0.
+        # When trying to cut a release v0.3.0-rc2, we need to base our comparisons on v0.3.0-rc1.
         run: |
           git fetch origin --tags
           go install github.com/marten-seemann/semver-highest@fcdc98f8820ff0e6613c1bee071c096febd98dbf
           vs=$(git tag | paste -sd , -)
           if [[ ! -z "$vs" ]]; then
-            v=$(semver-highest -target "$VERSION" -versions "$vs")
+            v=$(semver-highest -target "$VERSION" -versions "$vs" -prerelease="$PRERELEASE")
             status=$?
             if [[ $status != 0 ]]; then
               echo $v
